
"use client";

import { motion } from 'framer-motion';
import { Rocket } from 'lucide-react';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { type AnalyzeProjectOutput } from '@/ai/flows/analyze-project-flow';

export function AppIcon({ analysis, onIconClick }: { analysis: AnalyzeProjectOutput; onIconClick: () => void; }) {
  const { projectName, buildCommands, runCommand } = analysis;

  const handleDownloadAndReset = () => {
    // The "wave transmission" - generating a downloadable build script.
    const scriptContent = [
      '#!/bin/bash',
      '# Build script generated by Reality Command',
      `# Project: ${projectName}`,
      '',
      'echo "--- PREPARING ENVIRONMENT ---"',
      ...buildCommands.filter(cmd => cmd.toLowerCase().includes('venv') || cmd.toLowerCase().includes('source')),
      '',
      'echo "--- INSTALLING DEPENDENCIES ---"',
      ...buildCommands.filter(cmd => cmd.toLowerCase().includes('install')),
      '',
      'echo "--- RUNNING BUILD ---"',
      ...buildCommands.filter(cmd => !cmd.toLowerCase().includes('install') && !cmd.toLowerCase().includes('venv') && !cmd.toLowerCase().includes('source')),
      '',
      'echo "--- BUILD COMPLETE ---"',
      'echo "To run your application, execute the following command:"',
      `echo "> ${runCommand}"`
    ].join('\n');

    const blob = new Blob([scriptContent], { type: 'application/x-shellscript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');

    a.href = url;
    a.download = `${projectName.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}_build.sh`;
    document.body.appendChild(a);
    a.click();

    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    // Reset the simulation after the "transmission" is complete.
    onIconClick();
  };
  
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <motion.div
            initial={{ opacity: 0, scale: 0.5, y: 50 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.5, y: -50 }}
            onClick={handleDownloadAndReset}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="flex cursor-pointer flex-col items-center gap-4 p-8 rounded-2xl bg-card/50 border border-primary/30"
          >
            <div className="flex h-32 w-32 items-center justify-center rounded-2xl border-2 border-primary bg-card shadow-lg shadow-primary/20">
              <Rocket className="h-20 w-20 text-primary" />
            </div>
            <div className="text-center">
                <p className="text-xl font-bold text-foreground">{projectName}</p>
                <p className="text-sm text-muted-foreground">Transmit Build</p>
            </div>
          </motion.div>
        </TooltipTrigger>
        <TooltipContent side="bottom">
          <p>Download build script and reset simulation</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
