"use client";

import { useState, useEffect, useMemo, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Hammer, Package, FileCode, Puzzle, CheckCircle, ChevronRight, XCircle, Cog } from 'lucide-react';
import CodeBlock from '@/components/anitch/code-block';

// Types and constants
type Log = {
  id: number;
  type: 'command' | 'output' | 'success' | 'error' | 'info';
  message: string;
};

const buildScript = `#!/bin/bash
set -e

PYTHON="/Library/Developer/CommandLineTools/usr/bin/python3"
PY2APPLET="$HOME/Library/Python/3.9/bin/py2applet"

APP_NAME="ANITCH"
PY_ENTRY="main.py"

DOWNLOADS_PYCONFIG="$HOME/Downloads/pyconfig.h"

echo "=============================="
echo " ANITCH BUILD FORGE"
echo "=============================="

echo "[*] Using Python:"
$PYTHON --version

# Ask python where its include dir SHOULD be
PY_INCLUDE_DIR="$($PYTHON - << 'EOF'
import sysconfig
print(sysconfig.get_path("include") or "")
EOF
)"

echo "[*] Python include dir:"
echo "$PY_INCLUDE_DIR"

TARGET_PYCONFIG="$PY_INCLUDE_DIR/pyconfig.h"

# Ensure include dir exists
if [ ! -d "$PY_INCLUDE_DIR" ]; then
  echo "[!] Python include dir does not exist. Creating it..."
  mkdir -p "$PY_INCLUDE_DIR"
fi

# If pyconfig.h missing, try to pull from Downloads
if [ ! -f "$TARGET_PYCONFIG" ]; then
  echo "[!] pyconfig.h not found at:"
  echo "    $TARGET_PYCONFIG"

  if [ -f "$DOWNLOADS_PYCONFIG" ]; then
    echo "[*] Found fallback pyconfig.h in Downloads."
    echo "[*] Copying to Python include dir..."
    cp "$DOWNLOADS_PYCONFIG" "$TARGET_PYCONFIG"
  else
    echo "[X] No pyconfig.h found in Downloads either."
    echo "    Expected at: $DOWNLOADS_PYCONFIG"
    exit 1
  fi
fi

echo "[✓] pyconfig.h present:"
ls -l "$TARGET_PYCONFIG"

# Ensure py2applet exists
if [ ! -x "$PY2APPLET" ]; then
  echo "[!] py2applet not found. Installing py2app..."
  $PYTHON -m pip install --user py2app
fi

echo "[*] Using py2applet:"
echo "$PY2APPLET"

# Generate setup.py if missing
if [ ! -f setup.py ]; then
  echo "[*] Generating setup.py for ANITCH..."
  "$PY2APPLET" --make-setup "$PY_ENTRY"
fi

echo "[*] Building ANITCH.app with py2app..."
$PYTHON setup.py py2app

echo "=============================="
echo " BUILD COMPLETE"
echo " dist/\${APP_NAME}.app"
echo "=============================="
`;

const setupPyContent = `"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'anitch.icns',
    'plist': {
        'CFBundleName': 'ANITCH',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
`;

const simulationSteps = [
  { delay: 500, log: { type: 'output', message: '==============================' } },
  { delay: 200, log: { type: 'output', message: ' ANITCH BUILD FORGE' } },
  { delay: 200, log: { type: 'output', message: '==============================' } },
  { delay: 800, log: { type: 'info', message: '[*] Using Python:' } },
  { delay: 300, log: { type: 'output', message: 'Python 3.9.6' } },
  { delay: 800, log: { type: 'info', message: '[*] Python include dir:' } },
  { delay: 300, log: { type: 'output', message: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9' } },
  { delay: 800, log: { type: 'info', message: '[*] Checking for pyconfig.h...' } },
  { delay: 500, log: { type: 'error', message: '[!] pyconfig.h not found at specified path.' } },
  { delay: 800, log: { type: 'info', message: '[*] Found fallback pyconfig.h in Downloads. Copying...' } },
  { delay: 1200, log: { type: 'success', message: '[✓] pyconfig.h present:' } },
  { delay: 300, log: { type: 'output', message: '-rw-r--r-- 1 user staff 15318 May 28 10:14 /.../pyconfig.h' } },
  { delay: 800, log: { type: 'info', message: '[*] Checking for py2applet...' } },
  { delay: 500, log: { type: 'error', message: '[!] py2applet not found. Installing py2app...' } },
  { delay: 1500, log: { type: 'output', message: 'Collecting py2app...' } },
  { delay: 1200, log: { type: 'output', message: 'Successfully installed py2app-0.28.5' } },
  { delay: 300, log: { type: 'success', message: '[✓] Using py2applet: /Users/user/Library/Python/3.9/bin/py2applet' } },
  { delay: 800, log: { type: 'info', message: '[*] Generating setup.py for ANITCH...' } },
  { delay: 1200, log: { type: 'success', message: 'Wrote setup.py' } },
  { delay: 800, log: { type: 'info', message: '[*] Building ANITCH.app with py2app...' } },
  { delay: 800, log: { type: 'command', message: 'python setup.py py2app' } },
  { delay: 1200, log: { type: 'output', message: 'running py2app' } },
  { delay: 800, log: { type: 'output', 'message': 'creating /.../build/bdist.macosx-12-arm64/python3.9-standalone/app' } },
  { delay: 800, log: { type: 'output', 'message': 'creating /.../build/bdist.macosx-12-arm64/python3.9-standalone/app/collect' } },
  { delay: 1500, log: { type: 'output', 'message': 'creating /.../build/bdist.macosx-12-arm64/python3.9-standalone/app/temp' } },
  { delay: 1200, log: { type: 'output', 'message': 'performing clean build' } },
  { delay: 800, log: { type: 'output', 'message': 'creating /.../dist/ANITCH.app' } },
  { delay: 2000, log: { type: 'success', message: 'Done!' } },
  { delay: 300, log: { type: 'output', message: '==============================' } },
  { delay: 200, log: { type: 'output', message: ' BUILD COMPLETE' } },
  { delay: 200, log: { type: 'output', message: ' dist/ANITCH.app' } },
  { delay: 200, log: { type: 'success', message: '==============================' } },
];

const InfoItem = ({ icon: Icon, label, value }: { icon: React.ElementType, label: string, value: string }) => (
  <div className="flex items-start space-x-3">
    <div className="flex-shrink-0">
      <Icon className="h-5 w-5 text-accent" />
    </div>
    <div>
      <p className="text-sm text-muted-foreground">{label}</p>
      <p className="font-medium text-foreground">{value}</p>
    </div>
  </div>
);

const LogLine = ({ log }: { log: Log }) => {
  const Icon = useMemo(() => {
    switch (log.type) {
      case 'command': return Hammer;
      case 'success': return CheckCircle;
      case 'error': return XCircle;
      case 'info': return Cog;
      default: return ChevronRight;
    }
  }, [log.type]);

  const color = useMemo(() => {
    switch (log.type) {
      case 'success': return 'text-success';
      case 'error': return 'text-destructive';
      case 'info': return 'text-info';
      case 'command': return 'text-warning';
      default: return 'text-muted-foreground';
    }
  }, [log.type]);

  return (
    <div className="flex items-start space-x-2 font-code text-sm">
      <Icon className={`h-4 w-4 flex-shrink-0 mt-0.5 ${color}`} />
      <p className="flex-1 whitespace-pre-wrap break-words">{log.message}</p>
    </div>
  );
};

export default function Home() {
  const [logs, setLogs] = useState<Log[]>([]);
  const [isBuilding, setIsBuilding] = useState(false);
  const [progress, setProgress] = useState(0);
  const [showSetupPy, setShowSetupPy] = useState(false);
  const [buildComplete, setBuildComplete] = useState(false);
  const consoleRef = useRef<HTMLDivElement>(null);

  const startBuild = () => {
    setIsBuilding(true);
    setLogs([]);
    setProgress(0);
    setShowSetupPy(false);
    setBuildComplete(false);
    
    let currentDelay = 0;
    simulationSteps.forEach((step, index) => {
      currentDelay += step.delay;
      setTimeout(() => {
        setLogs(prev => [...prev, { ...step.log, id: prev.length }]);
        setProgress(((index + 1) / simulationSteps.length) * 100);
        
        if (step.log.message === 'Wrote setup.py') {
          setShowSetupPy(true);
        }

        if (index === simulationSteps.length - 1) {
          setIsBuilding(false);
          setBuildComplete(true);
        }
      }, currentDelay);
    });
  };

  useEffect(() => {
    if (consoleRef.current) {
      consoleRef.current.scrollTop = consoleRef.current.scrollHeight;
    }
  }, [logs]);


  return (
    <div className="min-h-screen bg-background text-foreground p-4 sm:p-6 md:p-8">
      <main className="max-w-7xl mx-auto space-y-8">
        <header className="flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-4 sm:space-y-0">
          <div>
            <h1 className="text-3xl md:text-4xl font-headline font-bold text-primary">ANITCH App Builder</h1>
            <p className="text-muted-foreground mt-1">Visualize your Python macOS app build process.</p>
          </div>
          <Button onClick={startBuild} disabled={isBuilding} size="lg" className="font-headline">
            {isBuilding ? <><Cog className="mr-2 h-4 w-4 animate-spin" /> Building...</> : buildComplete ? <><CheckCircle className="mr-2 h-4 w-4" /> Build Again</> : <><Hammer className="mr-2 h-4 w-4" /> Start Build</>}
          </Button>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
          <div className="lg:col-span-2 space-y-8">
            <Card className="overflow-hidden">
              <CardHeader>
                <CardTitle className="font-headline">Build Forge Console</CardTitle>
                <CardDescription>Live output from the simulated build process.</CardDescription>
              </CardHeader>
              <CardContent>
                <Progress value={progress} className="w-full h-2 mb-4" />
                <div ref={consoleRef} className="h-96 bg-secondary rounded-md p-4 overflow-y-auto space-y-2 border">
                  {logs.map((log) => <LogLine key={log.id} log={log} />)}
                  {isBuilding && logs.length > 0 && <div className="flex items-center space-x-2"><Cog className="h-4 w-4 animate-spin text-accent" /><span className="text-accent text-sm font-body">Processing...</span></div>}
                  {logs.length === 0 && <p className="text-muted-foreground text-center pt-16 font-body">Click "Start Build" to begin the simulation.</p>}
                </div>
              </CardContent>
            </Card>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
               <Card className={showSetupPy ? 'opacity-100 transition-opacity duration-700' : 'opacity-0 -z-10'}>
                <CardHeader>
                  <CardTitle className="font-headline">Generated setup.py</CardTitle>
                </CardHeader>
                <CardContent>
                  <CodeBlock content={setupPyContent} language="python" />
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="font-headline">Source Build Script</CardTitle>
                </CardHeader>
                <CardContent>
                  <CodeBlock content={buildScript} language="bash" />
                </CardContent>
              </Card>
            </div>
          </div>
          
          <div className="lg:col-span-1 space-y-8 lg:sticky lg:top-8">
            <Card>
              <CardHeader>
                <CardTitle className="font-headline">Script Analysis</CardTitle>
                <CardDescription>Key parameters detected from the script.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <InfoItem icon={Package} label="App Name" value="ANITCH" />
                <InfoItem icon={FileCode} label="Entry Point" value="main.py" />
                <InfoItem icon={Puzzle} label="Main Dependency" value="py2app" />
                <InfoItem icon={Hammer} label="Python Version" value="3.9+" />
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
