"use client";

import { useState, useRef, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { VideoOff, BotMessageSquare } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { useToast } from '@/hooks/use-toast';
import { analyzeProject, type AnalyzeProjectOutput } from '@/ai/flows/analyze-project-flow';
import { FileDropZone } from '@/components/anitch/FileDropZone';
import { AnalysisPanel } from '@/components/anitch/AnalysisPanel';
import { AppIcon } from '@/components/anitch/AppIcon';

export default function Home() {
  const { toast } = useToast();
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hasCameraPermission, setHasCameraPermission] = useState<boolean | null>(null);

  const [files, setFiles] = useState<File[]>([]);
  const [analysis, setAnalysis] = useState<AnalyzeProjectOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [showAppIcon, setShowAppIcon] = useState(false);

  useEffect(() => {
    const getCameraPermission = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
        }
        setHasCameraPermission(true);
      } catch (error) {
        console.error('Error accessing camera:', error);
        setHasCameraPermission(false);
        toast({
          variant: 'destructive',
          title: 'Camera Access Denied',
          description: 'Please enable camera permissions to use the AR experience.',
        });
      }
    };
    getCameraPermission();
  }, [toast]);

  const handleFileDrop = (acceptedFiles: File[]) => {
    setFiles(acceptedFiles);
    setAnalysis(null);
    setShowAppIcon(false);
  };

  const handleAnalyze = useCallback(async () => {
    if (files.length === 0) {
      toast({
        variant: 'destructive',
        title: 'No Files',
        description: 'Please drop some project files before analyzing.',
      });
      return;
    }
    setIsLoading(true);
    setShowAppIcon(false);

    try {
      const fileContents = await Promise.all(
        files.map(file =>
          new Promise<{ name: string; content: string }>((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve({ name: file.name, content: reader.result as string });
            reader.onerror = reject;
            reader.readAsText(file);
          })
        )
      );

      const result = await analyzeProject({ files: fileContents });
      setAnalysis(result);
    } catch (error) {
      console.error("Analysis failed:", error);
      toast({
        variant: "destructive",
        title: "Analysis Failed",
        description: "The AI could not process the provided files. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  }, [files, toast]);
  
  const handleDownloadScript = () => {
    if (!analysis) return;

    const scriptContent = [
        '#!/bin/bash',
        '# Generated by AR Build Environment',
        'set -e', // Exit immediately if a command exits with a non-zero status.
        ...analysis.buildCommands,
        analysis.runCommand,
    ].join('\n');

    const blob = new Blob([scriptContent], { type: 'text/x-shellscript' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'build.sh';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
        title: "Script Downloaded",
        description: "Your build.sh script is ready. Run it in your terminal.",
    });
  };
  
  const handleBuildComplete = () => {
    setTimeout(() => {
        setShowAppIcon(true);
    }, 500);
  }

  const resetState = () => {
    setFiles([]);
    setAnalysis(null);
    setIsLoading(false);
    setShowAppIcon(false);
  }

  return (
    <div className="min-h-screen w-full relative overflow-hidden bg-black font-mono">
      <video ref={videoRef} className="absolute top-0 left-0 w-full h-full object-cover z-0" autoPlay muted playsInline />
      <div className="absolute top-0 left-0 w-full h-full bg-black/60 z-10" />

      <main className="relative z-20 w-full h-screen flex items-center justify-center">
        {hasCameraPermission === false && (
             <div className="w-full h-full flex items-center justify-center">
                <Card className="max-w-md bg-destructive/50 backdrop-blur-lg border-destructive text-destructive-foreground">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2"><VideoOff /> Camera Access Denied</CardTitle>
                        <CardDescription className="text-destructive-foreground/80">Please enable camera permissions in your browser settings to use the AR experience.</CardDescription>
                    </CardHeader>
                </Card>
            </div>
        )}

        {hasCameraPermission && (
            <AnimatePresence mode="wait">
              {!analysis ? (
                <FileDropZone 
                  key="dropzone"
                  onFilesDropped={handleFileDrop} 
                  onAnalyze={handleAnalyze} 
                  files={files}
                  isLoading={isLoading} 
                />
              ) : (
                <AnalysisPanel 
                  key="analysis"
                  analysis={analysis}
                  onBuildComplete={handleBuildComplete}
                  onReset={resetState}
                />
              )}
            </AnimatePresence>
        )}

        <AnimatePresence>
          {showAppIcon && analysis && (
            <AppIcon 
              projectName={analysis.projectName} 
              onDrop={handleDownloadScript}
            />
          )}
        </AnimatePresence>

        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.5 }}
            className="absolute bottom-6 left-6 flex items-center gap-2 text-sm text-white/50"
        >
          <BotMessageSquare size={16} />
          <span>AR Build Environment v1.0</span>
        </motion.div>
      </main>
    </div>
  );
}
